-- MySQL Script generated by MySQL Workbench
-- Sun Dec 20 13:09:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`adres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adres` (
  `idadres` INT NOT NULL AUTO_INCREMENT,
  `Miasto` VARCHAR(45) NOT NULL,
  `Ulica` VARCHAR(45) NOT NULL,
  `Kod_pocztowy` VARCHAR(6) NULL,
  PRIMARY KEY (`idadres`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kontakt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kontakt` (
  `idkontakt` INT NOT NULL AUTO_INCREMENT,
  `numer_telefonu` VARCHAR(9) NULL,
  `email` VARCHAR(45) NULL,
  `strona` VARCHAR(45) NULL,
  PRIMARY KEY (`idkontakt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`podmiot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`podmiot` (
  `nip` VARCHAR(10) NOT NULL,
  `nazwa` VARCHAR(255) NOT NULL,
  `data_rozpoczecia_dg` DATE NOT NULL,
  `status_dg` ENUM("aktywna", "zawieszona") NULL,
  `czyPodejzany` BIT NOT NULL DEFAULT 0,
  `ksiega_pr_idksiegi` INT NOT NULL,
  `adres_idadres` INT NOT NULL,
  `kontakt_idkontakt` INT NOT NULL,
  PRIMARY KEY (`nip`),
  UNIQUE INDEX `nip_UNIQUE` (`nip` ASC) VISIBLE,
  INDEX `fk_podmiot_adres1_idx` (`adres_idadres` ASC) VISIBLE,
  INDEX `fk_podmiot_kontakt1_idx` (`kontakt_idkontakt` ASC) VISIBLE,
  CONSTRAINT `fk_podmiot_adres1`
    FOREIGN KEY (`adres_idadres`)
    REFERENCES `mydb`.`adres` (`idadres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_podmiot_kontakt1`
    FOREIGN KEY (`kontakt_idkontakt`)
    REFERENCES `mydb`.`kontakt` (`idkontakt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kontroler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kontroler` (
  `idkontroler` INT NOT NULL,
  `imie_nazwisko` VARCHAR(255) NOT NULL,
  `pesel` VARCHAR(11) NOT NULL,
  `data_ur` DATE NOT NULL,
  `data_zatrudnienia` DATE NOT NULL,
  `adres_idadres` INT NOT NULL,
  `kontakt_idkontakt` INT NOT NULL,
  PRIMARY KEY (`idkontroler`),
  INDEX `fk_kontroler_adres1_idx` (`adres_idadres` ASC) VISIBLE,
  INDEX `fk_kontroler_kontakt1_idx` (`kontakt_idkontakt` ASC) VISIBLE,
  CONSTRAINT `fk_kontroler_adres1`
    FOREIGN KEY (`adres_idadres`)
    REFERENCES `mydb`.`adres` (`idadres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kontroler_kontakt1`
    FOREIGN KEY (`kontakt_idkontakt`)
    REFERENCES `mydb`.`kontakt` (`idkontakt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`protokol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`protokol` (
  `IdKontroli` INT NOT NULL AUTO_INCREMENT,
  `podmiot_nip` VARCHAR(10) NOT NULL,
  `poczatek_kontroli` DATE NOT NULL,
  `koniec_kontroli` DATE NOT NULL,
  `Nieprawidlowosci` VARCHAR(1024) NULL DEFAULT 'brak nieprawidlowosci',
  PRIMARY KEY (`IdKontroli`, `podmiot_nip`),
  CONSTRAINT `fk_protokol_podmiot1`
    FOREIGN KEY (`podmiot_nip`)
    REFERENCES `mydb`.`podmiot` (`nip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`podatek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`podatek` (
  `idpodatek` INT NOT NULL AUTO_INCREMENT,
  `podstawa_prawna` VARCHAR(45) NOT NULL,
  `wysokosc` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`idpodatek`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`przychodyrozchody`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`przychodyrozchody` (
  `podmiot_nip` VARCHAR(10) NOT NULL,
  `okres_rozliczeniowy` YEAR NOT NULL,
  `przychody` DOUBLE NOT NULL,
  `rozchody` DOUBLE NOT NULL,
  `odliczony_VAT` DOUBLE NOT NULL,
  PRIMARY KEY (`podmiot_nip`),
  CONSTRAINT `fk_przychodyrozchody_podmiot1`
    FOREIGN KEY (`podmiot_nip`)
    REFERENCES `mydb`.`podmiot` (`nip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`faktury`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`faktury` (
  `numer_faktury` VARCHAR(45) NOT NULL,
  `Kwota` DOUBLE NOT NULL,
  `NIP` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `przychodyrozchody_podmiot_nip` VARCHAR(10) NOT NULL,
  `podatek` DOUBLE NOT NULL,
  PRIMARY KEY (`numer_faktury`),
  INDEX `fk_faktury_przychodyrozchody1_idx` (`przychodyrozchody_podmiot_nip` ASC) VISIBLE,
  CONSTRAINT `fk_faktury_przychodyrozchody1`
    FOREIGN KEY (`przychodyrozchody_podmiot_nip`)
    REFERENCES `mydb`.`przychodyrozchody` (`podmiot_nip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`protokol_has_kontroler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`protokol_has_kontroler` (
  `protokol_IdKontroli` INT NOT NULL,
  `kontroler_idkontroler` INT NOT NULL,
  PRIMARY KEY (`protokol_IdKontroli`, `kontroler_idkontroler`),
  INDEX `fk_protokol_has_kontroler_kontroler1_idx` (`kontroler_idkontroler` ASC) VISIBLE,
  INDEX `fk_protokol_has_kontroler_protokol1_idx` (`protokol_IdKontroli` ASC) VISIBLE,
  CONSTRAINT `fk_protokol_has_kontroler_protokol1`
    FOREIGN KEY (`protokol_IdKontroli`)
    REFERENCES `mydb`.`protokol` (`IdKontroli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_protokol_has_kontroler_kontroler1`
    FOREIGN KEY (`kontroler_idkontroler`)
    REFERENCES `mydb`.`kontroler` (`idkontroler`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
